name: CyberMissions
version: ${project.version}
main: net.zerotoil.cybermissions.CyberMissions
api-version: 1.16
authors: [ Kihsomray ]
description: Simple missions plugin
website: zerotoil.net

commands:
  cybermissions:
    aliases:
      - cms
      - cm
      - cyberm
      - cmissions
      - cybermission
      - missions
      - mission
